---
apiVersion: v2
name: edc-controlplane
description: EDC Control-Plane
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-controlplane
type: application
appVersion: "0.1.2"
version: 0.1.2
maintainers: []