---
apiVersion: v2
name: irs
description: A Helm chart for Kubernetes

type: application
version: 0.0.2
appVersion: "1.0.0"

dependencies:

  # HashiCorp Vault
  - name: vault
    alias: edc-vault
    version: 0.20.0
    repository: https://helm.releases.hashicorp.com
    condition: install.edc.vault

  # Omejdn Service
  - name: omejdn-service
    alias: edc-daps
    version: 0.0.1
    repository: "file://subcharts/omejdn-service"
    condition: install.edc.daps

  # EDC Consumer
  # PostgreSQL
  - name: postgresql
    alias: edc-consumer-database
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: install.edc.consumer

  # Control plane
  - name: edc-control-plane
    alias: edc-consumer-control-plane
    version: 0.0.1
    repository: "file://subcharts/edc-control-plane"
    condition: install.edc.consumer

  # Data plane
  - name: edc-data-plane
    alias: edc-consumer-data-plane
    version: 0.0.1
    repository: "file://subcharts/edc-data-plane"
    condition: install.edc.consumer

  # EDC Provider
  # PostgreSQL
  - name: postgresql
    alias: edc-provider-database
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: install.edc.provider

  # Control plane
  - name: edc-control-plane
    alias: edc-provider-control-plane
    version: 0.0.1
    repository: "file://subcharts/edc-control-plane"
    condition: install.edc.provider

  # Data plane
  - name: edc-data-plane
    alias: edc-provider-data-plane
    version: 0.0.1
    repository: "file://subcharts/edc-data-plane"
    condition: install.edc.provider

  # IRS ############################

  # Semantic Hub Service
  - name: semantic-hub
    alias: semantic-hub
    version: 0.0.1
    repository: "file://subcharts/semantic-hub"
    condition: install.semanticHub

  # Digital Twin Registry Database
  - name: postgresql
    alias: digital-twin-registry-database
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: install.digitalTwin

  # Digital Twin Registry
  - name: digital-twin-registry
    alias: digital-twin-registry
    version: 0.0.1
    repository: "file://subcharts/digital-twin-registry"
    condition: install.digitalTwin

  # KeyCloak Service
  - name: keycloak
    alias: keycloak
    version: 0.0.1
    repository: "file://subcharts/keycloak"
    condition: install.keycloak

  # IRS Provider Backend
  - name: irs-provider-backend
    alias: irs-provider-backend
    version: 0.0.1
    repository: "file://subcharts/irs-provider-backend"
    condition: install.irs.providerBackend

  # IRS
  - name: irs-helm
    alias: irs
    repository: https://catenax-ng.github.io/tx-item-relationship-service
    version: 5.0.9
    condition: irs.enabled

  # IRS Frontend Service
  - name: irs-frontend-service
    alias: irs-frontend
    version: 0.0.5
    repository: "file://subcharts/irs-frontend-service"
    condition: install.irs.frontend
