# Copyright (c) 2021,2022,2023
#       2022: ZF Friedrichshafen AG
#       2022: ISTOS GmbH
#       2022,2023: Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#       2022,2023: BOSCH AG
# Copyright (c) 2021,2022,2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0. *
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "irs.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
data:
  application.yaml: |-
    # Config overriding Spring Boot configuration
    {{- if not .Values.config.override }}
    server:
      trustedPort: {{ .Values.service.trustedPort }}

    irs:
      apiUrl: {{ tpl (.Values.irsUrl | default "http://localhost") . | quote }}

    blobstore:
      endpoint: {{ tpl (.Values.minioUrl | default "") . | quote }}
      accessKey: "${MINIO_ACCESS_KEY}" # taken from secret ENV
      secretKey: "${MINIO_SECRET_KEY}" # taken from secret ENV

    spring:
      security:
        oauth2:
          client:
            registration:
              keycloak:
                client-id: "${KEYCLOAK_OAUTH2_CLIENT_ID}" # taken from secret ENV
                client-secret: "${KEYCLOAK_OAUTH2_CLIENT_SECRET}" # taken from secret ENV
              portal:
                client-id: ${PORTAL_OAUTH2_CLIENT_ID} # taken from secret ENV
                client-secret: ${PORTAL_OAUTH2_CLIENT_SECRET} # taken from secret ENV
            provider:
              keycloak:
                token-uri: {{ tpl (.Values.keycloak.oauth2.clientTokenUri | default "http://localhost") . | quote }}
              portal:
                token-uri: {{ tpl (.Values.keycloak.oauth2.clientTokenUri | default "http://localhost") . | quote }}
          resourceserver:
            jwt:
              jwk-set-uri: {{ tpl (.Values.keycloak.oauth2.jwkSetUri | default "http://localhost") . | quote }}

    digitalTwinRegistry:
      descriptorEndpoint: {{ tpl (.Values.digitalTwinRegistry.descriptorEndpoint | default "") . | quote }}
      shellLookupEndpoint: {{ tpl (.Values.digitalTwinRegistry.shellLookupEndpoint | default "") . | quote }}
      discoveryFinderUrl: {{ tpl (.Values.digitalTwinRegistry.discoveryFinderUrl | default "") . | quote }}
      type: {{ tpl (.Values.digitalTwinRegistry.type | default "") . | quote }}

    semanticshub:
      url: {{ tpl (.Values.semanticshub.url | default "") . | quote }}
      pageSize: {{ tpl (.Values.semanticshub.pageSize | default "100") . }}
      modelJsonSchemaEndpoint: {{ tpl (.Values.semanticshub.modelJsonSchemaEndpoint | default "") . | quote }}
      defaultUrns: {{ tpl (.Values.semanticshub.defaultUrns | default "") . | quote }}
      {{- if .Values.semanticshub.localModels }}
      localModelDirectory: /app/semantic-models
      {{- end }}

    bpdm:
      bpnEndpoint: {{ tpl (.Values.bpdm.bpnEndpoint | default "") . | quote }}

    edc:
      controlplane:
        request-ttl: {{ .Values.edc.controlplane.request.ttl | default "PT10M" | quote }}
        endpoint:
          data: {{ tpl (.Values.edc.controlplane.endpoint.data | default (printf "http://%s%s" .Release.Name "-edc-controlplane:8181/api/v1/management")) . | quote }}
        provider-suffix: {{ tpl .Values.edc.controlplane.provider.suffix . | quote }}
        catalog-limit: {{ .Values.edc.controlplane.catalog.limit }}
        catalog-page-size: {{ .Values.edc.controlplane.catalog.pagesize }}
        api-key:
          header: {{ tpl (.Values.edc.controlplane.apikey.header | default "") . | quote }}
          secret: ${EDC_API_KEY_SECRET:} # taken from secret ENV

      submodel:
        request-ttl: {{ tpl .Values.edc.submodel.request.ttl . | default "PT10M" | quote }}
        path: {{ tpl (.Values.edc.submodel.path | default "/submodel") . | quote }}
        urn-prefix: {{ tpl (.Values.edc.submodel.urnprefix | default "/urn") . | quote }}

      catalog:
        cache:
          enabled: {{ .Values.edc.catalog.cache.enabled | default true }}
          ttl: {{ .Values.edc.catalog.cache.ttl | default "P1D" | quote }}
          maxCachedItems: {{ .Values.edc.catalog.cache.maxCachedItems | default 64000 }}
        policies:
          allowedNames: {{ .Values.edc.catalog.policies.allowedNames | default "" | quote }}

    ess:
      localBpn: {{ tpl (.Values.bpn | default "") . | quote }}
      localEdcEndpoint: {{ tpl (.Values.edc.provider.host | default "") . | quote }}
      irs:
        url: {{ tpl (.Values.irsUrl | default "") . | quote }}
      discovery:
        endpoint: {{ tpl (.Values.discovery.endpoint | default "") . | quote }}
        oAuthClientId: {{ .Values.discovery.oAuthClientId | default "portal" }}
        {{- if .Values.discovery.mockEdcAddress }}
        mockEdcAddress:
        {{- tpl (toYaml .Values.discovery.mockEdcAddress) . | nindent 10 }}
        {{- end }}
        {{- if .Values.ess.mockEdcResult }}
        mockEdcResult:
        {{- tpl (toYaml .Values.ess.mockEdcResult) . | nindent 10 }}
        {{- end }}
        {{- if .Values.ess.mockRecursiveEdcAsset }}
        mockRecursiveEdcAsset: {{ tpl (.Values.ess.mockRecursiveEdcAsset) . | quote }}
        {{- end }}
    {{- end }}

    apiAllowedBpn: {{ tpl (.Values.bpn | default "") . | quote }}

    {{- if .Values.config.content }}
    {{- tpl (toYaml .Values.config.content) . | nindent 4 }}
    {{- end }}
