apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "omejdn-server.fullname" . }}
spec:
  limits:
    - type: Container
      max:
        cpu: {{ .Values.resources.limits.cpu }}
        memory: {{ .Values.resources.limits.memory }}
