---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-control-plane.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.edc.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.edc.endpoints.control.port }}
      targetPort: control
      protocol: TCP
      name: control
    - port: {{ .Values.edc.endpoints.management.port }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.edc.endpoints.validation.port }}
      targetPort: validation
      protocol: TCP
      name: validation
    - port: {{ .Values.edc.endpoints.protocol.port }}
      targetPort: protocol
      protocol: TCP
      name: protocol
    - port: {{ .Values.edc.endpoints.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "edc-control-plane.selectorLabels" . | nindent 4 }}