blobstore:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

irs:
  job:
    cleanup:
      scheduler:
        completed: 0 * * * * *
        failed: 0 * * * * *
    jobstore:
      ttl:
        failed: PT1H
        completed: PT1H

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost
      client:
        provider:
          keycloak:
            token-uri: https://localhost

# ESS Module specific properties
ess:
  irs:
    url: http://localhost:8080