apiVersion: v1
kind: Service
metadata:
  name: {{ include "irs.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "irs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.trustedPort }}
      targetPort: http-trusted
      protocol: TCP
      name: http-trusted
    - port: {{ .Values.service.actuatorPort }}
      targetPort: actuator
      protocol: TCP
      name: actuator
  selector:
    {{- include "irs.selectorLabels" . | nindent 4 }}