name: "Sync main to IRS-Env"

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge main into catena-x-environments
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --no-tags --progress
          git checkout --progress -b catena-x-environments origin/catena-x-environments
          git merge origin/main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
