name: Tavern IRS API test

on:
  workflow_dispatch: # Trigger manually
    inputs:
      irs-host:
        type: choice
        description: IRS environment to test
        default: 'https://irs.int.demo.catena-x.net'
        required: true
        options:
          - 'https://irs.int.demo.catena-x.net'
          - 'https://irs.dev.demo.catena-x.net'
      irs-ess-host:
        type: string
        description: IRS-ESS environment to test
        default: 'https://irs-ess.int.demo.catena-x.net'
        required: true
      global-asset-id:
        type: string
        description: Global Asset ID to use for the tests
        default: 'urn:uuid:513d7be8-e7e4-49f4-a22b-8cd31317e454'
        required: true
      execution-ticket:
        type: string
        description: JIRA execution ticket to safe results in.
        default: 'TRI-910'
        required: true
  schedule:
    - cron: '0 1 * * 1-5' # At 01:00 on every day-of-week from Monday through Friday.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.7

      - name: Install dependencies
        run: |
          pip install pytest
          pip install py
          pip install tavern
          pip list

      - name: Run tests
        env:
          IRS_HOST: ${{ github.event.inputs.irs-host || 'https://irs.int.demo.catena-x.net' }}
          IRS_ESS_HOST: ${{ github.event.inputs.irs-ess-host || 'https://irs-ess.int.demo.catena-x.net' }}
          KEYCLOAK_HOST: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_OAUTH2_CLIENT_SECRET }}
          GLOBAL_ASSET_ID: ${{ github.event.inputs.global-asset-id || 'urn:uuid:513d7be8-e7e4-49f4-a22b-8cd31317e454' }}
        run: |
          python -m pytest local/testing/api-tests/irs-api-tests.tavern.yaml --junitxml=tavern-results.xml

      - name: Upload results
        if: always()
        env:
          JIRA_USERNAME: ${{ secrets.ORG_IRS_JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.ORG_IRS_JIRA_PASSWORD }}
          TEST_EXECUTION_TICKET: ${{ github.event.inputs.execution-ticket || 'TRI-910' }}
        # Remove tokens and upload the tavern results to JIRA Test execution
        run: |
          sed "s/access_tok.*:s = '.*'//g" tavern-results.xml | sed "s/Authorization: Bearer .*/Authorization:/g" | uniq > result.xml
          curl -H "Content-Type: multipart/form-data" \
          -u $JIRA_USERNAME:$JIRA_PASSWORD \
          -F 'file=@result.xml' \
          "https://jira.catena-x.net/rest/raven/1.0/import/execution/junit?testExecKey=$TEST_EXECUTION_TICKET"
